### ISSUE TITLE
Add DEFAULT item in the ringtone list

### ISSUE THREAD

**Issue by UniqueJoy** [kevalpatel2106/android-ringtone-picker#3]
### Like the image has ###
![screenshot_20180320-083858 01-picsay](https://user-images.githubusercontent.com/30648777/37634069-f1a843c4-2c1a-11e8-8148-949c7ac44224.png)

**Comment by UniqueJoy** [comment]
![screenshot_20180320-083858 01-picsay](https://user-images.githubusercontent.com/30648777/37633965-735b7644-2c1a-11e8-889d-a8425eaf1c52.png)

I want to mean like the image.

**Comment by kevalpatel2106** [comment]
@UniqueJoy Added this feature in [v1.2](https://github.com/kevalpatel2106/android-ringtone-picker/releases/tag/v1.2). Check updated readme.

**Comment by UniqueJoy** [comment]
thank you.. 

but facing problem,i have downloaded your sample apk, at first i select tone it plays and displays its info but right after that again when i tap PICK RINGTONE, app unfortunately stopped!! every time happening

**Comment by kevalpatel2106** [comment]
Did you try using v1.3? There was a bug in sample app that was fixed in v1.3 of the sample app.

**Comment by kevalpatel2106** [comment]
Hey, Is there any chance that you read my last comment?

**Comment by UniqueJoy** [comment]
i did v1.3 but having same issue sir
