### ISSUE TITLE
[Suggestion] New Logo for Android Ringtone Picker

### ISSUE THREAD

**Issue by zularizal** [kevalpatel2106/android-ringtone-picker#6]
Hello @kevalpatel2106 , I want to contribute to this project, I want to design a new logo for this project and it's free, do you want it ?

**Comment by kevalpatel2106** [comment]
@zularizal Yes definitely. It will be amazing. 😉

**Comment by kevalpatel2106** [comment]
@zularizal I think I will go with 2. What's your opinion?

**Comment by zularizal** [comment]
I think so. Okay, wait a moment I'll upload the logo to the drive.

**Comment by kevalpatel2106** [comment]
Okay. I think you should add the logo to the app directory and generate the PR for the logo. By that way, you get a chance to contribute this project. What do you say?

**Comment by zularizal** [comment]
Okay, I accept it. I will try to add that logo to the directory.

**Comment by zularizal** [comment]
Hello @kevalpatel2106  , I've added the logo files and icons to drive. Here's the link 

https://drive.google.com/open?id=1ZbxPNs0tSrvNJka3Eqa6Vn3x_G8BDL9L

And I also made pull request please check #7

**Comment by kevalpatel2106** [comment]
New icons are added in PR #7 .

**Comment by kevalpatel2106** [comment]
@zularizal Can you provide your Twitter handler? I need to mention it in read me.

**Comment by zularizal** [comment]
@kevalpatel2106 This is [@zularizal1](https://twitter.com/zularizal1)
